export interface FarmStand {
  id: string;
  name: string;
  description: string;
  image: string;
  rating: number;
  reviewCount: number;
  distance: string;
  isOpen: boolean;
  hours: string;
  address: string;
  city: string;
  phone: string;
  products: string[];
  latitude: number;
  longitude: number;
  isFavorite: boolean;
  features: string[];
  region: string;
}

export interface Review {
  id: string;
  farmId: string;
  userName: string;
  userAvatar: string;
  rating: number;
  date: string;
  text: string;
  helpful: number;
}

// Real Oregon Farm Stands - curated list for launch
export const OREGON_FARM_STANDS: FarmStand[] = [
  // Portland Metro Area
  {
    id: "1",
    name: "Sauvie Island Farms",
    description: "Historic family farm on Sauvie Island offering U-pick berries, pumpkins, and fresh seasonal produce. A Portland favorite for over 30 years.",
    image: "https://images.unsplash.com/photo-1500076656116-558758c991c1?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "12.3 mi",
    isOpen: true,
    hours: "8:00 AM - 6:00 PM",
    address: "20200 NW Sauvie Island Rd",
    city: "Portland",
    phone: "(503) 621-3988",
    products: ["Strawberries", "Blueberries", "Pumpkins", "Corn", "Tomatoes"],
    latitude: 45.6280,
    longitude: -122.8100,
    isFavorite: false,
    features: ["U-Pick", "Family Owned", "Cash & Card"],
    region: "Portland Metro",
  },
  {
    id: "2",
    name: "Kruger's Farm Market",
    description: "Award-winning farm market featuring fresh produce, a bakery, and beautiful sunflower fields. Home of the famous corn maze.",
    image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "14.1 mi",
    isOpen: true,
    hours: "9:00 AM - 6:00 PM",
    address: "17100 NW Sauvie Island Rd",
    city: "Portland",
    phone: "(503) 621-3489",
    products: ["Sunflowers", "Peaches", "Apples", "Pumpkins", "Baked Goods"],
    latitude: 45.6190,
    longitude: -122.8050,
    isFavorite: true,
    features: ["Corn Maze", "Sunflower Fields", "Bakery", "Kid Friendly"],
    region: "Portland Metro",
  },
  {
    id: "3",
    name: "Baird Family Orchards",
    description: "Third-generation orchard in the heart of Hood River Valley. Famous for our cherries, peaches, and stunning Mt. Hood views.",
    image: "https://images.unsplash.com/photo-1595855759920-86582396756a?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "58.2 mi",
    isOpen: true,
    hours: "9:00 AM - 5:00 PM",
    address: "5801 Baseline Dr",
    city: "Hood River",
    phone: "(541) 386-2558",
    products: ["Cherries", "Peaches", "Apples", "Pears", "Cider"],
    latitude: 45.6850,
    longitude: -121.5220,
    isFavorite: false,
    features: ["Orchard Views", "Mt. Hood Views", "Cider Tasting"],
    region: "Hood River",
  },
  {
    id: "4",
    name: "Draper Girls Country Farm",
    description: "Family farm offering fresh-pressed cider, U-pick apples, and homemade pies in the beautiful Hood River Valley.",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "60.5 mi",
    isOpen: true,
    hours: "10:00 AM - 5:00 PM",
    address: "6200 Hwy 35",
    city: "Hood River",
    phone: "(541) 352-6625",
    products: ["Apples", "Cider", "Pies", "Peaches", "Berries"],
    latitude: 45.6720,
    longitude: -121.5350,
    isFavorite: false,
    features: ["Fresh Cider", "Homemade Pies", "U-Pick Apples"],
    region: "Hood River",
  },
  // Willamette Valley
  {
    id: "5",
    name: "Gathering Together Farm",
    description: "Certified organic farm and restaurant in Philomath. Our farm-to-table restaurant serves dishes made with produce picked that morning.",
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "82.4 mi",
    isOpen: true,
    hours: "10:00 AM - 6:00 PM",
    address: "25159 Grange Hall Rd",
    city: "Philomath",
    phone: "(541) 929-4270",
    products: ["Organic Greens", "Herbs", "Tomatoes", "Squash", "Flowers"],
    latitude: 44.5380,
    longitude: -123.3670,
    isFavorite: true,
    features: ["Certified Organic", "Farm Restaurant", "CSA Available"],
    region: "Willamette Valley",
  },
  {
    id: "6",
    name: "Thompson Farms",
    description: "Family-owned farm in Salem growing fresh berries, vegetables, and herbs using sustainable practices.",
    image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "45.8 mi",
    isOpen: true,
    hours: "8:00 AM - 5:00 PM",
    address: "3520 Hazelgreen Rd NE",
    city: "Salem",
    phone: "(503) 393-2050",
    products: ["Strawberries", "Raspberries", "Blueberries", "Vegetables"],
    latitude: 44.9780,
    longitude: -122.9890,
    isFavorite: false,
    features: ["U-Pick Berries", "Sustainable", "Family Owned"],
    region: "Willamette Valley",
  },
  {
    id: "7",
    name: "Greenwillow Grains",
    description: "Small-batch grain farm offering heritage wheat, oats, and freshly milled flour. Perfect for bakers!",
    image: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "52.1 mi",
    isOpen: true,
    hours: "9:00 AM - 4:00 PM",
    address: "91205 Territorial Hwy",
    city: "Junction City",
    phone: "(541) 998-2350",
    products: ["Wheat Flour", "Oats", "Heritage Grains", "Cornmeal"],
    latitude: 44.2190,
    longitude: -123.2050,
    isFavorite: false,
    features: ["Heritage Grains", "Fresh Milled", "Artisan Quality"],
    region: "Willamette Valley",
  },
  // Southern Oregon
  {
    id: "8",
    name: "Fry Family Farm",
    description: "Organic vegetable farm in the Applegate Valley. We grow over 50 varieties of heirloom tomatoes!",
    image: "https://images.unsplash.com/photo-1592921870789-04563d55041c?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "268.5 mi",
    isOpen: true,
    hours: "10:00 AM - 5:00 PM",
    address: "2184 Ross Ln",
    city: "Medford",
    phone: "(541) 702-2456",
    products: ["Heirloom Tomatoes", "Peppers", "Eggplant", "Garlic", "Onions"],
    latitude: 42.3265,
    longitude: -122.8756,
    isFavorite: false,
    features: ["Certified Organic", "Heirloom Varieties", "50+ Tomato Types"],
    region: "Southern Oregon",
  },
  {
    id: "9",
    name: "Pennington Farms",
    description: "U-pick berry farm near Grants Pass famous for marionberries, blackberries, and homemade berry jams.",
    image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "272.3 mi",
    isOpen: true,
    hours: "8:00 AM - 6:00 PM",
    address: "11341 Williams Hwy",
    city: "Grants Pass",
    phone: "(541) 846-7550",
    products: ["Marionberries", "Blackberries", "Blueberries", "Jams", "Pies"],
    latitude: 42.2840,
    longitude: -123.3280,
    isFavorite: false,
    features: ["U-Pick", "Homemade Jams", "Berry Pies"],
    region: "Southern Oregon",
  },
  // Central Oregon
  {
    id: "10",
    name: "Rainshadow Organics",
    description: "High-desert organic farm specializing in root vegetables, greens, and herbs adapted to Central Oregon's unique climate.",
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "142.8 mi",
    isOpen: true,
    hours: "9:00 AM - 4:00 PM",
    address: "65085 Cline Falls Rd",
    city: "Bend",
    phone: "(541) 389-3456",
    products: ["Carrots", "Beets", "Kale", "Lettuce", "Herbs"],
    latitude: 44.0582,
    longitude: -121.3153,
    isFavorite: false,
    features: ["Certified Organic", "High Desert Grown", "CSA Program"],
    region: "Central Oregon",
  },
  {
    id: "11",
    name: "Smith Rock Farm",
    description: "Family farm near the famous Smith Rock with amazing views. Known for our sweet corn, melons, and pumpkins.",
    image: "https://images.unsplash.com/photo-1500076656116-558758c991c1?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "138.2 mi",
    isOpen: true,
    hours: "8:00 AM - 5:00 PM",
    address: "8005 NW Smith Rock Way",
    city: "Terrebonne",
    phone: "(541) 548-2890",
    products: ["Sweet Corn", "Melons", "Pumpkins", "Squash", "Peppers"],
    latitude: 44.3638,
    longitude: -121.1416,
    isFavorite: false,
    features: ["Scenic Views", "Fall Festival", "Corn Maze"],
    region: "Central Oregon",
  },
  // Coast
  {
    id: "12",
    name: "Nehalem River Ranch",
    description: "Grass-fed beef and lamb farm on the beautiful Oregon Coast. We also offer farm-fresh eggs and seasonal vegetables.",
    image: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "78.6 mi",
    isOpen: true,
    hours: "10:00 AM - 4:00 PM",
    address: "35505 Hwy 53",
    city: "Nehalem",
    phone: "(503) 368-5556",
    products: ["Grass-Fed Beef", "Lamb", "Eggs", "Vegetables"],
    latitude: 45.7050,
    longitude: -123.8780,
    isFavorite: false,
    features: ["Grass-Fed", "Pasture Raised", "Farm Tours"],
    region: "Coast",
  },
  // Eastern Oregon
  {
    id: "13",
    name: "Walla Walla Sweet Onion Farm",
    description: "Home of the famous sweet onions! We also grow garlic, shallots, and other alliums in the rich Walla Walla soil.",
    image: "https://images.unsplash.com/photo-1518977956812-cd3dbadaaf31?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "256.4 mi",
    isOpen: true,
    hours: "8:00 AM - 5:00 PM",
    address: "1892 W Pine St",
    city: "Milton-Freewater",
    phone: "(541) 938-3456",
    products: ["Sweet Onions", "Garlic", "Shallots", "Leeks"],
    latitude: 45.9334,
    longitude: -118.3873,
    isFavorite: false,
    features: ["Famous Onions", "Bulk Available", "Shipping"],
    region: "Eastern Oregon",
  },
  {
    id: "14",
    name: "Blue Mountain Berries",
    description: "High-elevation berry farm in the Blue Mountains. Our cool nights make for the sweetest berries in Oregon!",
    image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "278.9 mi",
    isOpen: true,
    hours: "7:00 AM - 3:00 PM",
    address: "62145 Tollgate Rd",
    city: "Pendleton",
    phone: "(541) 278-4567",
    products: ["Strawberries", "Raspberries", "Huckleberries", "Preserves"],
    latitude: 45.6721,
    longitude: -118.7886,
    isFavorite: false,
    features: ["Mountain Grown", "Wild Huckleberries", "Preserves"],
    region: "Eastern Oregon",
  },
  // More Portland Area
  {
    id: "15",
    name: "Helvetia Farms",
    description: "Historic dairy and produce farm in Washington County. Fresh milk, cheese, and seasonal vegetables from happy cows.",
    image: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "18.4 mi",
    isOpen: true,
    hours: "9:00 AM - 5:00 PM",
    address: "23780 NW West Union Rd",
    city: "Hillsboro",
    phone: "(503) 647-5678",
    products: ["Raw Milk", "Cheese", "Yogurt", "Vegetables", "Eggs"],
    latitude: 45.5820,
    longitude: -122.9150,
    isFavorite: false,
    features: ["Artisan Cheese", "Raw Milk", "Farm Fresh"],
    region: "Portland Metro",
  },
  {
    id: "16",
    name: "Bella Organic Farm",
    description: "Sauvie Island's premier organic pumpkin patch and produce stand. Home of the world-famous pumpkin trebuchet!",
    image: "https://images.unsplash.com/photo-1509622905150-fa66d3906e09?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "13.8 mi",
    isOpen: true,
    hours: "9:00 AM - 6:00 PM",
    address: "16205 NW Gillihan Rd",
    city: "Portland",
    phone: "(503) 621-9545",
    products: ["Pumpkins", "Gourds", "Corn", "Squash", "Sunflowers"],
    latitude: 45.6410,
    longitude: -122.8230,
    isFavorite: true,
    features: ["Pumpkin Trebuchet", "Corn Maze", "Organic", "Kid Friendly"],
    region: "Portland Metro",
  },
  // Additional Portland Metro Produce Stands
  {
    id: "17",
    name: "Sherwood Orchards",
    description: "Family orchard since 1952 offering fresh apples, pears, and the best apple cider donuts in the Tualatin Valley.",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "22.1 mi",
    isOpen: true,
    hours: "9:00 AM - 5:30 PM",
    address: "22055 SW Pacific Hwy",
    city: "Sherwood",
    phone: "(503) 625-1248",
    products: ["Apples", "Pears", "Apple Cider", "Donuts", "Pies"],
    latitude: 45.3570,
    longitude: -122.8410,
    isFavorite: false,
    features: ["Cider Donuts", "U-Pick Apples", "Family Owned"],
    region: "Portland Metro",
  },
  {
    id: "18",
    name: "Clackamas Berry Farm",
    description: "U-pick berry paradise with over 15 varieties of berries. Fresh-baked berry pies available daily!",
    image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "15.6 mi",
    isOpen: true,
    hours: "7:00 AM - 7:00 PM",
    address: "16135 SE 82nd Dr",
    city: "Clackamas",
    phone: "(503) 656-3449",
    products: ["Strawberries", "Blueberries", "Raspberries", "Marionberries", "Berry Pies"],
    latitude: 45.4180,
    longitude: -122.5730,
    isFavorite: false,
    features: ["U-Pick", "15+ Berry Varieties", "Fresh Pies"],
    region: "Portland Metro",
  },
  {
    id: "19",
    name: "Forest Grove Farmstand",
    description: "Roadside produce stand with the freshest vegetables, local honey, and homemade jams. Cash only!",
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "28.3 mi",
    isOpen: true,
    hours: "8:00 AM - 6:00 PM",
    address: "3250 Pacific Ave",
    city: "Forest Grove",
    phone: "(503) 357-2890",
    products: ["Tomatoes", "Peppers", "Cucumbers", "Honey", "Jams"],
    latitude: 45.5200,
    longitude: -123.1100,
    isFavorite: false,
    features: ["Roadside Stand", "Local Honey", "Cash Only"],
    region: "Portland Metro",
  },
  // Bake Stands
  {
    id: "20",
    name: "Willamette Valley Pie Company",
    description: "Award-winning pie bakery using fresh Oregon berries and fruits. Try our famous marionberry pie!",
    image: "https://images.unsplash.com/photo-1535920527002-b35e96722eb9?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "48.2 mi",
    isOpen: true,
    hours: "7:00 AM - 7:00 PM",
    address: "2994 82nd Ave NE",
    city: "Salem",
    phone: "(503) 362-8678",
    products: ["Marionberry Pie", "Apple Pie", "Peach Cobbler", "Fruit Tarts", "Cookies"],
    latitude: 44.9650,
    longitude: -122.9580,
    isFavorite: true,
    features: ["Award Winning", "Fresh Baked Daily", "Oregon Berries"],
    region: "Willamette Valley",
  },
  {
    id: "21",
    name: "The Cookie Tree",
    description: "Charming bakery stand on a small farm offering fresh-baked cookies, brownies, and pastries.",
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "35.4 mi",
    isOpen: true,
    hours: "10:00 AM - 4:00 PM",
    address: "8890 Cascade Hwy SE",
    city: "Sublimity",
    phone: "(503) 769-3450",
    products: ["Cookies", "Brownies", "Scones", "Cinnamon Rolls", "Coffee"],
    latitude: 44.8260,
    longitude: -122.7890,
    isFavorite: false,
    features: ["Fresh Baked", "Farm Setting", "Coffee Available"],
    region: "Willamette Valley",
  },
  {
    id: "22",
    name: "Hood River Lavender Farm & Bakery",
    description: "Beautiful lavender farm with a bakery featuring lavender-infused treats and stunning Gorge views.",
    image: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "62.8 mi",
    isOpen: true,
    hours: "10:00 AM - 5:00 PM",
    address: "3801 Straight Hill Rd",
    city: "Hood River",
    phone: "(541) 386-7878",
    products: ["Lavender Scones", "Lavender Cookies", "Lavender Honey", "Dried Lavender", "Essential Oils"],
    latitude: 45.7120,
    longitude: -121.4890,
    isFavorite: false,
    features: ["Lavender Fields", "Gorge Views", "Artisan Bakery"],
    region: "Hood River",
  },
  // More Produce Stands
  {
    id: "23",
    name: "Springwater Farm",
    description: "Organic vegetable farm with an on-site farm stand. Known for incredible heirloom tomatoes and greens.",
    image: "https://images.unsplash.com/photo-1592921870789-04563d55041c?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "19.8 mi",
    isOpen: true,
    hours: "9:00 AM - 5:00 PM",
    address: "26789 SE Borges Rd",
    city: "Damascus",
    phone: "(503) 658-3320",
    products: ["Heirloom Tomatoes", "Salad Greens", "Herbs", "Squash", "Peppers"],
    latitude: 45.4250,
    longitude: -122.4180,
    isFavorite: false,
    features: ["Certified Organic", "Heirloom Varieties", "CSA Available"],
    region: "Portland Metro",
  },
  {
    id: "24",
    name: "Canby Asparagus Farm",
    description: "Spring asparagus specialists with the freshest spears in the valley. Also growing strawberries and rhubarb.",
    image: "https://images.unsplash.com/photo-1515471209610-dae1c92d8777?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "24.5 mi",
    isOpen: true,
    hours: "8:00 AM - 4:00 PM",
    address: "11250 S Kropf Rd",
    city: "Canby",
    phone: "(503) 266-4510",
    products: ["Asparagus", "Strawberries", "Rhubarb", "Sweet Corn"],
    latitude: 45.2630,
    longitude: -122.6920,
    isFavorite: false,
    features: ["Fresh Cut Daily", "Seasonal Specialty", "Family Farm"],
    region: "Portland Metro",
  },
  {
    id: "25",
    name: "McMinnville Farmers Market Stand",
    description: "Permanent farmstand offering the best of Yamhill County: wine country produce, cheese, and artisan goods.",
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "42.1 mi",
    isOpen: true,
    hours: "9:00 AM - 6:00 PM",
    address: "330 NE Baker St",
    city: "McMinnville",
    phone: "(503) 472-3450",
    products: ["Artisan Cheese", "Wine", "Fresh Produce", "Olive Oil", "Bread"],
    latitude: 45.2100,
    longitude: -123.1990,
    isFavorite: false,
    features: ["Wine Country", "Artisan Goods", "Local Cheese"],
    region: "Willamette Valley",
  },
  {
    id: "26",
    name: "Eugene Farm Direct",
    description: "Co-op farmstand bringing together the best produce from Lane County's organic farms.",
    image: "https://images.unsplash.com/photo-1500076656116-558758c991c1?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "108.5 mi",
    isOpen: true,
    hours: "8:00 AM - 7:00 PM",
    address: "1450 Willamette St",
    city: "Eugene",
    phone: "(541) 484-2890",
    products: ["Organic Produce", "Local Eggs", "Bread", "Flowers", "Mushrooms"],
    latitude: 44.0521,
    longitude: -123.0868,
    isFavorite: false,
    features: ["Co-op", "100% Local", "Organic Focus"],
    region: "Willamette Valley",
  },
  // Coastal Stands
  {
    id: "27",
    name: "Tillamook Creamery Farm Store",
    description: "Famous cheese factory with farm store offering fresh cheese curds, ice cream, and coastal dairy products.",
    image: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "74.2 mi",
    isOpen: true,
    hours: "8:00 AM - 6:00 PM",
    address: "4165 Hwy 101 N",
    city: "Tillamook",
    phone: "(503) 815-1300",
    products: ["Cheese", "Cheese Curds", "Ice Cream", "Butter", "Yogurt"],
    latitude: 45.4720,
    longitude: -123.8450,
    isFavorite: true,
    features: ["World Famous", "Factory Tours", "Fresh Cheese Curds"],
    region: "Coast",
  },
  {
    id: "28",
    name: "Astoria Sunday Market Stand",
    description: "Year-round produce stand near the historic Astoria waterfront with the freshest coastal vegetables.",
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "96.8 mi",
    isOpen: true,
    hours: "10:00 AM - 3:00 PM",
    address: "12th & Commercial St",
    city: "Astoria",
    phone: "(503) 325-1010",
    products: ["Kale", "Root Vegetables", "Seafood", "Mushrooms", "Berries"],
    latitude: 46.1879,
    longitude: -123.8313,
    isFavorite: false,
    features: ["Waterfront Location", "Fresh Seafood", "Year-Round"],
    region: "Coast",
  },
  {
    id: "29",
    name: "Newport Bayfront Bake Shop",
    description: "Coastal bakery famous for fresh clam chowder bread bowls and Oregon berry pastries.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "134.2 mi",
    isOpen: true,
    hours: "7:00 AM - 5:00 PM",
    address: "628 SW Bay Blvd",
    city: "Newport",
    phone: "(541) 265-3456",
    products: ["Bread Bowls", "Clam Chowder", "Berry Danish", "Crab Rolls", "Cookies"],
    latitude: 44.6318,
    longitude: -124.0530,
    isFavorite: false,
    features: ["Ocean Views", "Fresh Seafood", "Local Favorite"],
    region: "Coast",
  },
  // Central Oregon Additions
  {
    id: "30",
    name: "Sisters Farm Stand",
    description: "Charming roadside stand in the shadow of the Three Sisters mountains. Known for sweet corn and mountain berries.",
    image: "https://images.unsplash.com/photo-1500076656116-558758c991c1?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "156.3 mi",
    isOpen: true,
    hours: "9:00 AM - 5:00 PM",
    address: "69015 Camp Polk Rd",
    city: "Sisters",
    phone: "(541) 549-2890",
    products: ["Sweet Corn", "Berries", "Squash", "Pumpkins", "Honey"],
    latitude: 44.2908,
    longitude: -121.5490,
    isFavorite: false,
    features: ["Mountain Views", "Roadside Stand", "Local Honey"],
    region: "Central Oregon",
  },
  {
    id: "31",
    name: "Redmond Roots Farm",
    description: "High desert organic farm specializing in root vegetables and cold-hardy greens.",
    image: "https://images.unsplash.com/photo-1518977956812-cd3dbadaaf31?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "148.7 mi",
    isOpen: true,
    hours: "10:00 AM - 4:00 PM",
    address: "2345 NW Maple Ave",
    city: "Redmond",
    phone: "(541) 548-3456",
    products: ["Carrots", "Potatoes", "Beets", "Turnips", "Winter Greens"],
    latitude: 44.2726,
    longitude: -121.1739,
    isFavorite: false,
    features: ["High Desert Grown", "Root Vegetables", "Organic"],
    region: "Central Oregon",
  },
  // Southern Oregon Additions
  {
    id: "32",
    name: "Ashland Artisan Bakery",
    description: "European-style bakery near the Oregon Shakespeare Festival. Fresh breads, croissants, and pastries daily.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "285.6 mi",
    isOpen: true,
    hours: "7:00 AM - 6:00 PM",
    address: "38 E Main St",
    city: "Ashland",
    phone: "(541) 488-2890",
    products: ["Sourdough Bread", "Croissants", "Danish", "Baguettes", "Tarts"],
    latitude: 42.1946,
    longitude: -122.7095,
    isFavorite: false,
    features: ["European Style", "Fresh Daily", "Near Theater"],
    region: "Southern Oregon",
  },
  {
    id: "33",
    name: "Rogue Valley Produce",
    description: "Farmer's cooperative stand offering the best fruits and vegetables from the Rogue Valley.",
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "274.8 mi",
    isOpen: true,
    hours: "8:00 AM - 6:00 PM",
    address: "1234 Table Rock Rd",
    city: "Medford",
    phone: "(541) 772-3456",
    products: ["Pears", "Peaches", "Tomatoes", "Peppers", "Melons"],
    latitude: 42.3478,
    longitude: -122.8212,
    isFavorite: false,
    features: ["Co-op", "Local Farmers", "Rogue Valley Pears"],
    region: "Southern Oregon",
  },
  // Eastern Oregon Additions
  {
    id: "34",
    name: "Joseph Farmers Market",
    description: "Small-town charm with big flavors. Local produce and crafts from the Wallowa Valley.",
    image: "https://images.unsplash.com/photo-1500076656116-558758c991c1?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "328.4 mi",
    isOpen: true,
    hours: "9:00 AM - 2:00 PM",
    address: "201 N Main St",
    city: "Joseph",
    phone: "(541) 432-1234",
    products: ["Mountain Vegetables", "Lamb", "Beef", "Honey", "Crafts"],
    latitude: 45.3543,
    longitude: -117.2296,
    isFavorite: false,
    features: ["Mountain Town", "Local Meat", "Artisan Crafts"],
    region: "Eastern Oregon",
  },
  {
    id: "35",
    name: "Baker City Heritage Farm",
    description: "Historic farm stand along the Oregon Trail. Fresh produce and old-fashioned hospitality.",
    image: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "302.1 mi",
    isOpen: true,
    hours: "8:00 AM - 5:00 PM",
    address: "2890 10th St",
    city: "Baker City",
    phone: "(541) 523-4567",
    products: ["Corn", "Beans", "Squash", "Melons", "Potatoes"],
    latitude: 44.7749,
    longitude: -117.8344,
    isFavorite: false,
    features: ["Oregon Trail History", "Heritage Varieties", "Family Farm"],
    region: "Eastern Oregon",
  },
  {
    id: "36",
    name: "La Grande Valley Gardens",
    description: "University town farm stand with student-grown organic produce and educational programs.",
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "264.8 mi",
    isOpen: true,
    hours: "10:00 AM - 4:00 PM",
    address: "1505 Adams Ave",
    city: "La Grande",
    phone: "(541) 962-3456",
    products: ["Salad Mix", "Herbs", "Tomatoes", "Peppers", "Flowers"],
    latitude: 45.3246,
    longitude: -118.0878,
    isFavorite: false,
    features: ["Student Run", "Educational", "Organic"],
    region: "Eastern Oregon",
  },
  // More Willamette Valley
  {
    id: "37",
    name: "Corvallis Farm & Bakery",
    description: "OSU college town favorite with organic produce and fresh-baked goods from local grains.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "85.6 mi",
    isOpen: true,
    hours: "8:00 AM - 6:00 PM",
    address: "501 SW 2nd St",
    city: "Corvallis",
    phone: "(541) 752-3456",
    products: ["Artisan Bread", "Produce", "Local Grains", "Pastries", "Coffee"],
    latitude: 44.5646,
    longitude: -123.2620,
    isFavorite: false,
    features: ["Artisan Bakery", "Local Grains", "College Town"],
    region: "Willamette Valley",
  },
  {
    id: "38",
    name: "Albany Berry Farms",
    description: "Multi-generational berry farm with U-pick fields and fresh berry ice cream stand.",
    image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "72.3 mi",
    isOpen: true,
    hours: "7:00 AM - 6:00 PM",
    address: "33890 Oakville Rd S",
    city: "Albany",
    phone: "(541) 926-7890",
    products: ["Strawberries", "Raspberries", "Blackberries", "Berry Ice Cream", "Jam"],
    latitude: 44.6266,
    longitude: -123.1059,
    isFavorite: false,
    features: ["U-Pick", "Ice Cream Stand", "Fresh Jam"],
    region: "Willamette Valley",
  },
  {
    id: "39",
    name: "Silverton Garden Market",
    description: "Charming farmstand in the gateway to Silver Falls. Fresh flowers, produce, and garden starts.",
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "52.8 mi",
    isOpen: true,
    hours: "9:00 AM - 5:00 PM",
    address: "105 N Water St",
    city: "Silverton",
    phone: "(503) 873-2345",
    products: ["Cut Flowers", "Garden Starts", "Vegetables", "Herbs", "Honey"],
    latitude: 44.9996,
    longitude: -122.7830,
    isFavorite: false,
    features: ["Near Silver Falls", "Fresh Flowers", "Garden Starts"],
    region: "Willamette Valley",
  },
  {
    id: "40",
    name: "Woodburn Tulip Farm Stand",
    description: "Famous tulip fields with seasonal farmstand offering bulbs, cut flowers, and local produce.",
    image: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800",
    rating: 0,
    reviewCount: 0,
    distance: "35.2 mi",
    isOpen: true,
    hours: "9:00 AM - 6:00 PM",
    address: "33814 S Meridian Rd",
    city: "Woodburn",
    phone: "(503) 634-2243",
    products: ["Tulips", "Bulbs", "Cut Flowers", "Berries", "Vegetables"],
    latitude: 45.1437,
    longitude: -122.8547,
    isFavorite: true,
    features: ["Tulip Fields", "U-Pick Flowers", "Spring Festival"],
    region: "Willamette Valley",
  },
];

// Keep MOCK_FARM_STANDS as alias for backwards compatibility
export const MOCK_FARM_STANDS = OREGON_FARM_STANDS;

export const MOCK_REVIEWS: Review[] = [];

export const PRODUCT_FILTERS = [
  "All",
  "Berries",
  "Vegetables",
  "Fruits",
  "Organic",
  "U-Pick",
  "Dairy",
  "Meat",
  "Baked Goods",
];

export const OREGON_REGIONS = [
  "All Oregon",
  "Portland Metro",
  "Hood River",
  "Willamette Valley",
  "Southern Oregon",
  "Central Oregon",
  "Coast",
  "Eastern Oregon",
];
