/**
 * Imported Farmstand Data - From spreadsheet/CSV imports
 * All farmstands here are UNCLAIMED and UNVERIFIED by default
 */

export interface ImportedFarmstandRow {
  farmstand_name: string;
  street_address: string;
  city: string;
  state: string;
  zip: string;
  full_address_as_listed: string;
  description: string;
  hours_text: string;
  payment_methods: string;
  products: string;
  tags: string;
  source: string;
  notes: string;
}

// Data imported from Facebook Ads manual entry - January 2026
export const IMPORTED_FARMSTANDS: ImportedFarmstandRow[] = [
  {
    farmstand_name: "Lorenz Farmstand",
    street_address: "10861 Wheatland Rd",
    city: "Gervais",
    state: "OR",
    zip: "",
    full_address_as_listed: "10861 Wheatland Rd, Gervais, OR",
    description: "Farmstand now open! Eggs, Honey, Baked Goods! Open mostly Sundays for now. 10am–3pm. Select Saturdays include 10–4. Cash,paypal,cashapp,venmo,zelle, all accepted!",
    hours_text: "open! eggs, honey, baked goods! open mostly sundays for now; select saturdays include 10–4",
    payment_methods: "Cash, PayPal, Cash App, Venmo, Zelle",
    products: "Baked Goods, Eggs, Honey",
    tags: "baked_goods, eggs, honey",
    source: "facebook_ads_manual_entry",
    notes: "Imported from ad screenshots; verify address formatting & hours.",
  },
  {
    farmstand_name: "Wildlings Cottage Farmstand",
    street_address: "56574 Old Portland Rd",
    city: "Warren",
    state: "OR",
    zip: "",
    full_address_as_listed: "56574 Old Portland Rd, Warren, OR",
    description: "Jar bouquets $15 or 2/$25. Bring your mom, wife, girlfriend or friend flowers—treat yourself. Come get them soon!",
    hours_text: "",
    payment_methods: "",
    products: "Flowers",
    tags: "flowers",
    source: "facebook_ads_manual_entry",
    notes: "Imported from ad screenshots; verify address formatting & hours.",
  },
  {
    farmstand_name: "NE 143rd Farmstand",
    street_address: "1715 NE 143rd Ave",
    city: "Portland",
    state: "OR",
    zip: "97230",
    full_address_as_listed: "1715 NE 143rd Ave, Portland, Oregon 97230",
    description: "Farm stand open Saturdays and Sundays 9–6. On 143rd between San Raphael and Halsey right across from the Glendover Golf Course. Check photos for items we sell.",
    hours_text: "open saturdays and sundays 9–6; Sat–Sun 9am–6pm",
    payment_methods: "",
    products: "",
    tags: "",
    source: "facebook_ads_manual_entry",
    notes: "Imported from ad screenshots; verify address formatting & hours.",
  },
  {
    farmstand_name: "The Little Jar Farmstand",
    street_address: "8529 NW Poverty Bend Rd",
    city: "",
    state: "OR",
    zip: "",
    full_address_as_listed: "8529 NW Poverty Bend Rd",
    description: "Locally made canned goods, breads, cookies. Beeswax candles, crochet keychains. Eggs. Follow the little jar Farmstand for updates. Facebook and Instagram.",
    hours_text: "",
    payment_methods: "",
    products: "Bread, Candles, Canned Goods, Cookies, Eggs, Handmade",
    tags: "baked_goods, candles, canned_goods, eggs, handmade",
    source: "facebook_ads_manual_entry",
    notes: "Imported from ad screenshots; verify address formatting & hours.",
  },
  {
    farmstand_name: "Brightwood Loop Farmstand",
    street_address: "Country Club Rd by Brightwood Loop Rd",
    city: "Brightwood",
    state: "OR",
    zip: "",
    full_address_as_listed: "Country Club Rd by Brightwood Loop Rd, Brightwood, OR",
    description: "Farmstand is stocked and ready! Sourdough loaves, cinnamon rolls, sourdough chocolate chip cookies, blueberry sour cream coffee cake muffins. Open Friday, Saturday, and Sunday 9am till dark.",
    hours_text: "open friday, saturday, and sunday 9am till dark; Fri–Sun 9am–dark",
    payment_methods: "",
    products: "Cinnamon Rolls, Cookies, Muffins, Sourdough",
    tags: "baked_goods",
    source: "facebook_ads_manual_entry",
    notes: "Imported from ad screenshots; verify address formatting & hours.",
  },
  {
    farmstand_name: "Oxbow Pkwy Farmstand",
    street_address: "5410 SE Oxbow Pkwy",
    city: "Gresham",
    state: "OR",
    zip: "",
    full_address_as_listed: "5410 SE Oxbow Pkwy, Gresham",
    description: "Farmstand open 7 days a week from 9am–6pm. Featuring: Vanilla granola, Peanut butter granola, Taco seasoning, Cajun seasoning, Ranch dip mix, Spring simmer pot kits, Hot cocoa mix, Apple cider mix, Freeze dried treats and candies, Firewood bundles. We accept cash, Venmo, and Zelle.",
    hours_text: "open 7 days a week from 9am–6pm; Daily 9am–6pm",
    payment_methods: "Cash, Venmo, Zelle",
    products: "Drink Mixes, Firewood, Freeze-Dried Treats, Granola, Seasonings",
    tags: "firewood, pantry, snacks",
    source: "facebook_ads_manual_entry",
    notes: "Imported from ad screenshots; verify address formatting & hours.",
  },
  // New imports - January 2026 batch
  {
    farmstand_name: "Farmstand Sourdough",
    street_address: "385 S Cherry Dr",
    city: "Cornelius",
    state: "OR",
    zip: "97113",
    full_address_as_listed: "385 S Cherry Dr, Cornelius OR 97113",
    description: "Sourdough breads, scones, focaccia and farm eggs. Open daily 6am–5pm.",
    hours_text: "Open daily 6am–5pm",
    payment_methods: "",
    products: "Sourdough, Scones, Focaccia, Eggs",
    tags: "baked_goods, eggs, sourdough",
    source: "manual_admin_seed",
    notes: "Imported from spreadsheet data.",
  },
  {
    farmstand_name: "Farm Stand Open in Newberg",
    street_address: "24050 NE Wildwood Rd",
    city: "Newberg",
    state: "OR",
    zip: "",
    full_address_as_listed: "24050 NE Wildwood Rd, Newberg OR",
    description: "Self-serve farm stand.",
    hours_text: "",
    payment_methods: "",
    products: "",
    tags: "self_serve",
    source: "manual_admin_seed",
    notes: "Imported from spreadsheet data.",
  },
  {
    farmstand_name: "Harvest Farm Stand",
    street_address: "Camp Creek Rd mile 5.5",
    city: "McKenzie Fire Station area",
    state: "OR",
    zip: "",
    full_address_as_listed: "Camp Creek Rd mile 5.5, McKenzie Fire Station area",
    description: "Fall harvest farmstand with produce and seasonal goods.",
    hours_text: "",
    payment_methods: "",
    products: "Produce, Seasonal Goods",
    tags: "produce, seasonal",
    source: "manual_admin_seed",
    notes: "Imported from spreadsheet data.",
  },
  {
    farmstand_name: "Farmstand",
    street_address: "36 Jewel Ct",
    city: "Depoe Bay",
    state: "OR",
    zip: "97341",
    full_address_as_listed: "36 Jewel Ct, Depoe Bay OR 97341",
    description: "Fresh sourdough, muffins, danishes and jams. Sourdough baked goods.",
    hours_text: "",
    payment_methods: "",
    products: "Sourdough, Muffins, Danishes, Jams",
    tags: "baked_goods, sourdough, jams",
    source: "manual_admin_seed",
    notes: "Imported from spreadsheet data.",
  },
  {
    farmstand_name: "Farm stand",
    street_address: "Jansen Ln",
    city: "Boring",
    state: "OR",
    zip: "",
    full_address_as_listed: "Jansen Ln, Boring OR",
    description: "Sourdough bread, scones and cookies. Honor system.",
    hours_text: "",
    payment_methods: "",
    products: "Sourdough, Scones, Cookies",
    tags: "baked_goods, sourdough, honor_system",
    source: "manual_admin_seed",
    notes: "Imported from spreadsheet data.",
  },
  {
    farmstand_name: "Sourdough Self Serve Farm Stand",
    street_address: "83259 Territorial Hwy",
    city: "Eugene",
    state: "OR",
    zip: "97405",
    full_address_as_listed: "83259 Territorial Hwy, Eugene OR 97405",
    description: "Self-serve sourdough baked goods. Cinnamon roll Sundays.",
    hours_text: "Cinnamon roll Sundays",
    payment_methods: "",
    products: "Sourdough, Cinnamon Rolls",
    tags: "baked_goods, sourdough, self_serve",
    source: "manual_admin_seed",
    notes: "Imported from spreadsheet data.",
  },
  {
    farmstand_name: "Non Toxic Candles",
    street_address: "",
    city: "Sisters",
    state: "OR",
    zip: "",
    full_address_as_listed: "Sisters OR",
    description: "Self-serve farmstand selling soy candles.",
    hours_text: "",
    payment_methods: "",
    products: "Soy Candles",
    tags: "candles, handmade, self_serve",
    source: "manual_admin_seed",
    notes: "Imported from spreadsheet data.",
  },
  {
    farmstand_name: "Potpourri kits",
    street_address: "West Beacon Hill",
    city: "Longview",
    state: "WA",
    zip: "",
    full_address_as_listed: "West Beacon Hill, Longview WA",
    description: "Potpourri kits with dried citrus, lavender and cinnamon.",
    hours_text: "",
    payment_methods: "",
    products: "Potpourri Kits",
    tags: "handmade, gifts",
    source: "manual_admin_seed",
    notes: "Imported from spreadsheet data.",
  },
  {
    farmstand_name: "Farm Stand Goods",
    street_address: "Totem Pole Rd",
    city: "Lebanon",
    state: "OR",
    zip: "",
    full_address_as_listed: "Totem Pole Rd, Lebanon OR",
    description: "Freeze dried goods, canned goods, eggs, chicken and salmon.",
    hours_text: "",
    payment_methods: "",
    products: "Freeze-Dried Goods, Canned Goods, Eggs, Chicken, Salmon",
    tags: "eggs, canned_goods, meat, freeze_dried",
    source: "manual_admin_seed",
    notes: "Imported from spreadsheet data.",
  },
  {
    farmstand_name: "Salt Creek Goods Farmstand",
    street_address: "15726 Salt Creek Rd",
    city: "Dallas",
    state: "OR",
    zip: "",
    full_address_as_listed: "15726 Salt Creek Rd, Dallas OR",
    description: "Baked goods with gluten-free options. Open Wed/Fri/Sat/Sun 11am–8pm. Cash & Venmo.",
    hours_text: "Open Wed/Fri/Sat/Sun 11am–8pm",
    payment_methods: "Cash, Venmo",
    products: "Baked Goods, Gluten-Free Options",
    tags: "baked_goods, gluten_free",
    source: "manual_admin_seed",
    notes: "Imported from spreadsheet data.",
  },
  {
    farmstand_name: "Milagro Farmstand",
    street_address: "1139 Old 99S",
    city: "",
    state: "OR",
    zip: "",
    full_address_as_listed: "1139 Old 99S, OR",
    description: "Organically grown produce: heirloom tomatoes, peppers, okra, radishes. Self-serve.",
    hours_text: "",
    payment_methods: "",
    products: "Heirloom Tomatoes, Peppers, Okra, Radishes",
    tags: "produce, organic, self_serve",
    source: "manual_admin_seed",
    notes: "Imported from spreadsheet data.",
  },
  {
    farmstand_name: "Windmill Springs Farm",
    street_address: "1578 Sleepy Hollow Loop",
    city: "",
    state: "OR",
    zip: "",
    full_address_as_listed: "1578 Sleepy Hollow Loop",
    description: "Storefront open daily 8am–7pm. Jams, cider, syrups, seasonings. Cash & Venmo.",
    hours_text: "Open daily 8am–7pm",
    payment_methods: "Cash, Venmo",
    products: "Jams, Cider, Syrups, Seasonings",
    tags: "jams, cider, pantry",
    source: "manual_admin_seed",
    notes: "Imported from spreadsheet data.",
  },
  {
    farmstand_name: "Hilltop Homestead Farmstand",
    street_address: "Kerby Mainline",
    city: "Kerby",
    state: "OR",
    zip: "",
    full_address_as_listed: "Kerby Mainline, Kerby OR",
    description: "Fresh sourdough, cookies, treats. Open Thu–Sat 10am–7pm.",
    hours_text: "Open Thu–Sat 10am–7pm",
    payment_methods: "",
    products: "Sourdough, Cookies, Treats",
    tags: "baked_goods, sourdough",
    source: "manual_admin_seed",
    notes: "Imported from spreadsheet data.",
  },
  {
    farmstand_name: "Jacksonville Hill Farmstand",
    street_address: "Jacksonville Hill & Cady Rd",
    city: "Jacksonville",
    state: "OR",
    zip: "",
    full_address_as_listed: "Jacksonville Hill & Cady Rd, Jacksonville OR",
    description: "Fresh sourdough breads, cookies, cinnamon rolls. Follow on FB & Instagram.",
    hours_text: "",
    payment_methods: "",
    products: "Sourdough, Cookies, Cinnamon Rolls",
    tags: "baked_goods, sourdough",
    source: "manual_admin_seed",
    notes: "Imported from spreadsheet data.",
  },
];
